from pygame import Vector2

# WINDOW SIZE
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480

# SCREEN
BORDER_WIDTH = 20
SHOW_CONTROLS = True

# COLORS AND FONT
BG_COLOR = "#443554"
BORDER_COLOR = "#19151c"
BULLET_COLOR = "#da9df2"
FONT_COLOR = "#bc7ad6"
FONT = "utils/font.ttf"

# PLAYER LOGIC
PLAYER_RADIUS = 7
LIVES = 5
POINTS = 0
POINT_MULTIPLIER = 0.9 # 1.0 when game begins
MAX_POINTS = 5000
CURR_ANGLE = 0
INVINCIBLE_TIME = 1500
INVINCIBLE_TIMER = 0
INVINCIBLE = False
SHAKE_DURATION = 100
SHAKE_MAG = 7
SHAKE_TIMER = 0
SHAKE_OFFSET = Vector2(0, 0)

# BULLET LOGIC
BULLET_SPEED = 300
ROTATION_SPEED = 300